<h1> Soal 1: Pemahaman Tentang Model Evaluasi</h1>

Jawab pertanyaan di bawah ini dengan bahasa masing-masing?

1. Apa perbedaan antara data latih, data validasi, dan data test?
2. Bagaimana cara kita menilai performa suatu model?
3. Apa itu Confusion Matrix? Jelaskan secara lengkap!
4. Apa itu Classification Report dari sklearn?

Jawab:

1. Data latih merupakan data yang kita latih untuk membuat prediksi atau menjalankan fungsi dari sebuah algoritma ML. Data validasi merupakan data hasil evaluasi model yang memiliki bias yang kecil. Data test merupakan data yang kita tes untuk melihat keakuratannya, atau dengan kata lain melihat performanya
2. Dalam mengevaluasi generalisai performa sebuah Machine Learning ada beberapa teknik yang dapat digunakan yaitu (training dan testing) dan k-fold cross validation.
3. Confusion Matrix bisa disebut juga dengan error matrix. Confusion Matrix lebih detai dalam kategori tebakan. Confusion matrix memberikan informasi perbandingan hasil klasifikasi yang dilakukan oleh sistem (model) dengan hasil klasifikasi sebenarnya. Confusion matrix berbentuk tabel matriks yang menggambarkan kinerja model klasifikasi pada serangkaian data uji yang nilai sebenarnya diketahui. Dalam accurasi hanya ada dua, yaitu tebakan benar dan tebakan salah, sedangkan pada confusion matrix ada empat: 1. tebakan benar (model menenbak: positif), 2. tebakan salah (model menenbak: positif), 3. tebakan benar (model menenbak: negatif), 4. tebakan salah (model menenbak: negatif).
4. Classification Report merupakan suatu Laporan Klasifikasi digunakan untuk mengukur kualitas prediksi dari algoritma klasifikasi. Classification Report dari sklearn bertujuan untuk membuat laporan teks yang menunjukkan metrik klasifikasi utama.

---

<h1>Soal 2: Aplikasi Model Evaluasi</h1>

Kali ini kita akan menggunakan data untuk memprediksi kelangsungan hidup pasien yang telah mengalami operasi payudara. Dengan informasi yang dimiliki terkait pasien, kita akan membuat model untuk memprediksi apakah pasien akan bertahan hidup dalam waktu lebih dari 5 tahun atau tidak.

Lebih Lengkapnya kalian bisa membaca informasi tentang dataset di link berikut: https://raw.githubusercontent.com/jbrownlee/Datasets/master/haberman.names

Buat model Klasifikasi (Model/Algoritma Bebas) untuk memprediksi status pasien dengan ketentuan sebagai berikut:

1. Bagi kedua data ini menjadi data training dan data test dengan test_size=0.25.
3. Pelajar tentang metrics roc_auc_score kemudian buatlah model dan evaluasi dengan menggunakan teknik cross-validation dengan scoring 'roc_auc'. Baca https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html untuk menggunakan metric roc_auc saat cross-validation.
3. Berapa score rata2 dari model dengan teknik cross-validation tersebut?
4. Prediksi data test dengan model yang telah kalian buat!
5. Bagaimana hasil confusion matrix dari hasil prediksi tersebut?
6. Bagaimana classification report dari hasil prediksi tersebut?
5. Seberapa baik model anda dalam memprediksi seorang pasien mempunyai status positive?
6. Seberapa baik model anda dalam memprediksi seorang pasien mempunyai status negatif?

In [45]:
import pandas as pd
list_cols = ['Age', "Patient's Years", "N_positive_ax", "survival_status"]
df = pd.read_csv('https://raw.githubusercontent.com/jbrownlee/Datasets/master/haberman.csv', names=list_cols)

In [31]:
df.head()

Age  Patient's Years  N_positive_ax  survival_status
0   30               64              1                1
1   30               62              3                1
2   30               65              0                1
3   31               59              2                1
4   31               65              4                1

In [32]:
df['survival_status'].value_counts()

1    225
2     81
Name: survival_status, dtype: int64

In [36]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import roc_auc_score

X = df.drop('survival_status', axis=1)
y = df['survival_status']

In [34]:
# Validasi k-fold validation
# pilih n_neighbors=20
model_knn = KNeighborsClassifier(n_neighbors=20)
cv_score = cross_val_score(model_knn, X, y, cv=10, scoring='roc_auc')
cv_score.mean()

0.702084705753184

In [35]:
# 1
# Split data train dan data test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=21, stratify=y)

# Lakukan train model dan prediksi data test
model_knn.fit(X_train, y_train)
y_predict_train = model_knn.predict(X_train)
y_predict_test = model_knn.predict(X_test)

In [39]:
# Validasi hasil prediksi data train dan test
# Hasil score tidak berbeda jauh, model sudah cukup bagus
from sklearn.metrics import accuracy_score 
print('Score data train', accuracy_score(y_train, y_predict_train))
print('Score data test', accuracy_score(y_test, y_predict_test))

Score data train 0.7729257641921398
Score data test 0.7272727272727273


In [38]:
# 2 & 3
y_predict = model_knn.predict(X_test)
print('ROC AUC Score data train', roc_auc_score(y_train, y_predict_train))
print('ROC AUC Score data test', roc_auc_score(y_test, y_predict))

ROC AUC Score data train 0.6103142076502733
ROC AUC Score data test 0.5885964912280702


In [40]:
# 4
y_predict

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1,
       1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2,
       1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2], dtype=int64)

In [8]:
# 5 & 6
# Pengukuran dengan confusion matrix dan classification report
from sklearn.metrics import confusion_matrix, classification_report
cf_matrix = confusion_matrix(y_test, y_predict_test)
print(cf_matrix)

cf_report = classification_report(y_test, y_predict_test)
print(cf_report)


[[50  7]
 [14  6]]
              precision    recall  f1-score   support

           1       0.78      0.88      0.83        57
           2       0.46      0.30      0.36        20

    accuracy                           0.73        77
   macro avg       0.62      0.59      0.60        77
weighted avg       0.70      0.73      0.71        77



7) Seberapa baik model anda dalam memprediksi seorang pasien mempunyai status positive?
- Jawaban: Dalam memprediksi status positif model ini cukup baik dengan score precission 78%, recal 88% dan f1-score 83%

8) Seberapa baik model anda dalam memprediksi seorang pasien mempunyai status negatif?
- Jawaban: Sedangkan dalam memprediksi status negatif model ini tidak bagus karena menghasilkan score yang rendah yaitu: precission 46%, recal 30% dan f1-score 36%

---

<h1> Soal 3: Pemahaman Tentang Model Selection</h1>

Jelaskan dengan bahasa sendiri!

1. Apa itu Bias dan Variance?
2. Apa itu Overfitting dan Underfitting?
3. Apa yang bisa kita lakukan untuk mengatur kompleksitas dari model?
4. Bagaimana model yang baik?
5. Kapan kita menggunakan GridSearchcv dan kapan menggunakan RandomizedSearchCV?

Jawab:

1. Bias adalah perbedaan antara rata rata hasil prediksi dari model ML yang kita develop dengan data nilai yang sebenarnya.Variance adalah variabel dari prediksi model untuk data tertentu dimana memberikan kita informasi perserbaran data kita. 
2. Overfitting adalah suatu keadaan dimana data yang digunakan untuk pelatihan itu adalah yang "terbaik". Sehingga apabila dilakukan tes dengan menggunakan data yang berbeda dapat mengurangi akurasi (hasil yang dibuat tidak sesuai yang diharapkan).Underfitting adalah keadaan dimana model pelatihan data yang dibuat tidak mewakilkan keseluruhan data yang akan digunakan nantinya. Sehingga menghasilkan performa yang buruk dalam pelatihan data. Underfitting terjadi karena model masih mempelajari struktur dari data.
3. Mentuning hyperparameter
4. Dikatakan model yang baik jika error rates pada training dataset dan test dataset rendah (atau dapat dikatakan juga memiliki bieas error yang kecil dan variance error yang kecil)
5. GridSearchcv digunakan pada saat kumpulan data yang sedikit dan memiliki hyperparameter banyak, sedangkan RandomizedSearchCV digunakan saat kumpulan data yang banyak dan memiliki hyperparameter banyak

---

<h1> Soal 4: Aplikasi Model Selection</h1>

1. Bagi kedua data berikut ini menjadi data training dan data test dengan test_size=0.25.
2. Gunakan algoritma KNN sebagai model classifier.
3. Gunakan fungsi GridSearchCV untuk hyperparameter tuning dan model selection.
4. jumlah fold bebas!, gunakan scoring 'roc_auc'
5. Definisikan kombinasi hyperparameter untuk model selection dengan GridSearchCV. kombinasi Hyperparameter bebas, baca lagi dokumentasi KNN di link berikut https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html untuk memahami lagi jenis2 hyperparameter di algorithma KNN.
6. Latih model terhadap data training.
7. Apa hyperparameter terbaik untuk kombinasi hyperparameter kalian?
8. Berapa score validasi terbaik dari model tersebut?
9. Prediksi probabilitasi output dari model yang telah di buat terhadap data test. note : gunakan method .predict_proba() untuk menghasilkan output probabilitas
10. Perhatikan bahwa hasil prediksi ada 2, dimana masing2 adalah nilai probabilitas untuk setiap class label. Ambil nilai probabilitas pasien phositive meninggal dalam waktu kurang dari 5 tahun. note : gunakan bantuan attirubte .classes_ untuk mengetahui urutan label dari hasil prediksi probabilitas.
11. Berapa nilai score roc_auc untuk data test?
12. Apakah model anda termasuk baik, overtting, atau underfitting?
13. Ulangi tahap di atas namun kali ini menggunakan algoritma DecisionTreeClassifier dan kalian bisa menggunakan RandomizedSearchCV apabila process training lama. pelajari algoritma DecisionTreeClassifier di linkberikut: https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html?highlight=decisiontreeclassifier#sklearn.tree.DecisionTreeClassifier
14. Bandingkan scorenya dengan Algoritma KNN, mana yang lebih baik?

Note : Data Science adalah experiment, sangat di dimungkinkan memerlukan beberapa kali percobaan untuk mendapatkan hasil yang terbaik! Happy Coding :)

In [44]:
import pandas as pd

list_cols = ['Age', "Patient's Years", "N_positive_ax", "survival_status"]
df = pd.read_csv('https://raw.githubusercontent.com/jbrownlee/Datasets/master/haberman.csv', names=list_cols)

In [10]:
df.head()

Age  Patient's Years  N_positive_ax  survival_status
0   30               64              1                1
1   30               62              3                1
2   30               65              0                1
3   31               59              2                1
4   31               65              4                1

In [41]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
import numpy as np

X = df.drop('survival_status', axis=1)
y = df['survival_status']

In [42]:
# Pemilihan hyperparameter dengan GridSearchCV
model_knn = KNeighborsClassifier()
params = {'n_neighbors':np.arange(5,50),'weights':['uniform','distance'],
          'algorithm':['ball_tree','kd_tree','brute']}
gscv = GridSearchCV(model_knn,param_grid=params,scoring='roc_auc',cv=10)
gscv.fit(X, y)

GridSearchCV(cv=10, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
                         'weights': ['uniform', 'distance']},
             scoring='roc_auc')

In [43]:
# Mendapatkan parameter terbaik
print(gscv.best_params_)
print(gscv.best_score_)

{'algorithm': 'kd_tree', 'n_neighbors': 48, 'weights': 'uniform'}
0.7359903381642512


In [14]:
# Split data train dan test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=21, stratify=y)

In [15]:
# Setup model dengan parameter terbaik hasil dari GridSearchCV
model_knn = KNeighborsClassifier(algorithm='kd_tree', n_neighbors=48, weights='uniform')

# Train model tsb
model_knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='kd_tree', n_neighbors=48)

In [16]:
# Prediksi data train dan test
y_predict_train = model_knn.predict(X_train)
y_predict_test = model_knn.predict(X_test)


In [17]:
# Score validasi data train dan test
from sklearn.metrics import accuracy_score 
print('Score data train', accuracy_score(y_train, y_predict_train))
print('Score data test', accuracy_score(y_test, y_predict_test))

Score data train 0.7554585152838428
Score data test 0.7402597402597403


In [18]:
# Score validasi data train dan test dg roc_auc
from sklearn.metrics import roc_auc_score 
print('ROC AUC Score data train', roc_auc_score(y_train, y_predict_train))
print('ROC AUC Score data test', roc_auc_score(y_test, y_predict_test))

ROC AUC Score data train 0.5514246682279469
ROC AUC Score data test 0.5486842105263158


In [19]:
# Pengukuran dengan confusion matrix dan classification report
from sklearn.metrics import confusion_matrix, classification_report
cf_matrix = confusion_matrix(y_test, y_predict_test)
print(cf_matrix)

cf_report = classification_report(y_test, y_predict_test)
print(cf_report)

[[54  3]
 [17  3]]
              precision    recall  f1-score   support

           1       0.76      0.95      0.84        57
           2       0.50      0.15      0.23        20

    accuracy                           0.74        77
   macro avg       0.63      0.55      0.54        77
weighted avg       0.69      0.74      0.68        77



In [20]:
prob = model_knn.predict_proba(X_test)
df_prob = pd.DataFrame(prob,columns=['positif','negatif'])
df_prob.head()

positif   negatif
0  0.833333  0.166667
1  0.729167  0.270833
2  0.708333  0.291667
3  0.541667  0.458333
4  0.708333  0.291667

In [21]:
print('probabilitas pasien positif ', df_prob['positif'].mean())
print('probabilitas pasien negatif ', df_prob['negatif'].mean())

probabilitas pasien positif  0.741612554112554
probabilitas pasien negatif  0.25838744588744583


#12
Model termasuk goodfitting

In [22]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
import numpy as np

regressor = DecisionTreeRegressor()
params = {'random_state':np.arange(0,20),'criterion':['mse','mae'],
          'splitter':['best','random'],'max_depth':np.arange(2,10)} 
#rscv = RandomizedSearchCV(regressor, params, scoring='accuracy', cv=5)
#rscv.fit(X,y)

gscv = GridSearchCV(regressor,param_grid=params,scoring='roc_auc',cv=10)
gscv.fit(X, y)

GridSearchCV(cv=10, estimator=DecisionTreeRegressor(),
             param_grid={'criterion': ['mse', 'mae'],
                         'max_depth': array([2, 3, 4, 5, 6, 7, 8, 9]),
                         'random_state': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]),
                         'splitter': ['best', 'random']},
             scoring='roc_auc')

In [23]:
# Mendapatkan parameter terbaik
print(gscv.best_params_)
print(gscv.best_score_)

{'criterion': 'mse', 'max_depth': 5, 'random_state': 0, 'splitter': 'random'}
0.693854351472924


In [24]:
# Mendapatkan parameter terbaik
print(gscv.best_params_)
print(gscv.best_score_)

{'criterion': 'mse', 'max_depth': 5, 'random_state': 0, 'splitter': 'random'}
0.693854351472924


In [25]:
# Setup model dengan parameter terbaik hasil dari GridSearchCV
model = DecisionTreeRegressor(criterion= 'mse', max_depth=5, random_state=0, splitter='random')

# Train model tsb
model.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=5, random_state=0, splitter='random')

In [26]:
# Prediksi data train dan test
y_predict_train = model.predict(X_train)
y_predict_test = model.predict(X_test)

In [27]:
# Score validasi data train dan test
from sklearn.metrics import accuracy_score 
print('Score data train', accuracy_score(y_train, np.floor(y_predict_train)))
print('Score data test', accuracy_score(y_test, np.floor(y_predict_test)))

Score data train 0.7510917030567685
Score data test 0.7532467532467533


In [29]:
# Score validasi data train dan test dg roc_auc
from sklearn.metrics import roc_auc_score 
print('ROC AUC Score data train', roc_auc_score(y_train, y_predict_train))
print('ROC AUC Score data test', roc_auc_score(y_test, y_predict_test))

ROC AUC Score data train 0.7957650273224043
ROC AUC Score data test 0.6833333333333333


In [28]:
from sklearn.metrics import confusion_matrix, classification_report
cf_matrix = confusion_matrix(y_test, np.floor(y_predict_test))
print(cf_matrix)

cf_report = classification_report(y_test, np.floor(y_predict_test))
print(cf_report)

[[57  0]
 [19  1]]
              precision    recall  f1-score   support

           1       0.75      1.00      0.86        57
           2       1.00      0.05      0.10        20

    accuracy                           0.75        77
   macro avg       0.88      0.53      0.48        77
weighted avg       0.81      0.75      0.66        77



Model termasuk goodfitting

#14
Berdasarkan pemaparan di atas, model yang terbaik adalah model Decision Tree Regressor